language: python

python:
    - "3.6"

services: postgresql

env:
    global:
        - DJANGO_SETTINGS_MODULE="api.settings"
        - PYTHONPATH="/home/travis/build/samuel-l/checklistshare"
        - PIP_USE_MIRRORS=true
        - BUILD_ON_TRAVIS=true
    matrix:
        - DJANGO=2.0 DB=postgresql

install:
    - pip install -q Django==$DJANGO
    - pip install -q -r requirements.txt

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - python api/manage.py migrate

script:
    python api/manage.py test api
