# Generated by Django 2.0.5 on 2018-05-06 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
