# Generated by Django 2.0.5 on 2018-05-07 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checklist',
            new_name='List',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='checklist',
            new_name='List',
        ),
    ]
