# Generated by Django 2.0.5 on 2018-05-25 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_auto_20180507_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seq',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='List',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklist.List'),
        ),
    ]
